project:
  type: book
number-depth: 1
lang: en-GB
license: "CC BY"
book:
  title: Hardware documentation Guide
  author: Julien Colomb
  date: 2025-08-15
  search: true
  repo-url: https://codeberg.org/openmake/Hardware-template-guide/
  repo-subdir: 91_Explanation_book
  repo-actions:
  - issue

  downloads:
  - pdf
  - epub
  chapters:
  - index.qmd
  - content/960_prototypingasstep1_conc.qmd
  - content/130_metadata.qmd
  - content/106_readme_main_conc.qmd
  - content/019_Community_-_work_culture_conc.qmd
  - content/034_product_dvt_-requirements_conc.qmd
  - content/047_FSB_intro_conc.qmd
  - content/105_Product_build-main_conc.qmd
  - content/051_Project_history_-changelog.md_conc.qmd
  - content/104_user_guides_Overview_conc.qmd
  - content/200-sources.qmd
format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreport
  epub:
    toc: true
editor: visual
